### ISSUE TITLE
Confirming Device Before Purchasing

### ISSUE THREAD

**Issue by MTWiley** [imnotbob/OrbitValve#1]
Just wanted to make sure I was looking at the right device since I can't seem to find it based on the model number in your readme.   Is this the right item?

https://www.lowes.com/pd/Orbit-Iris-Hose-Faucet-Water-Timer-Works-With-Iris/50140356

Or if not can you provide me with a link to where I can buy it?

**Comment by imnotbob** [comment]
That is the ones I have
